# Generated by Django 5.0.6 on 2024-05-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellido')),
                ('cedula', models.TextField(unique=True, verbose_name='Número de Cédula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('celular', models.CharField(max_length=255, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('descripcionDiscapacidad', models.TextField(verbose_name='Descripción de discapacidad')),
            ],
        ),
    ]
