# Generated by Django 5.0.6 on 2024-05-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postulante',
            new_name='postulantes',
        ),
    ]
