# Generated by Django 5.0.6 on 2024-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0002_rename_postulante_postulantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nit', models.TextField(unique=True, verbose_name='Número de NIT')),
                ('rut', models.TextField(unique=True, verbose_name='Número de RUT')),
                ('telefono', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
