# Generated by Django 5.0.6 on 2024-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0003_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='confirmacion_contraseña',
            field=models.CharField(default='some string', max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='contraseña',
            field=models.CharField(default='some string', max_length=255, verbose_name='Contraseña'),
        ),
    ]
